# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\TeyvatToolKit\teyvatUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_TeyvatUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 152)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_reliquery = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_reliquery.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_reliquery.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_reliquery.setObjectName("lineEdit_reliquery")
        self.horizontalLayout.addWidget(self.lineEdit_reliquery)
        self.pushButton_reliquery = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reliquery.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_reliquery.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_reliquery.setObjectName("pushButton_reliquery")
        self.horizontalLayout.addWidget(self.pushButton_reliquery)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "提瓦特工具包"))
        self.label_2.setText(_translate("MainWindow", "圣遗物评分，请先输入uid："))
        self.pushButton_reliquery.setText(_translate("MainWindow", "评分"))
